### ISSUE TITLE
Implement floating position for bookmark icons to ensure they visible if the paragraph is visible

### ISSUE THREAD

**Issue by seanmturley** [seanmturley/shavian-stories#44]
# Description

When paragraphs are longer than the view port height there is the risk that the bookmark icon will be off screen if it's simply centered vertically relative to the paragraph height. Ideally, this icon should "float" to a certain extent, so that it always remains visible so long as the paragraph itself is in a readable part of the view port.

# Implementation

Earlier experimentation produced the following CSS to achieve something like what is desired:

```CSS
.parent {
  display: flex;
  margin-bottom: var(--story-line-height);
}

.icon {
  position: sticky;
  --number-of-lines-threshold: 5;
  top: calc(50% - 0.5 * var(--number-of-lines-threshold) * var(--story-line-height));
  max-height: calc(var(--number-of-lines-threshold) * var(--story-line-height));
  display: flex;
  align-items: center;
}

.parent p {
  margin: 0;
}
```
Unfortunately the HTML structure for those experiments wasn't preserved, but it was probably something like:

``` html
<div className={styles.parent}>
   <div className={styles.icon}>B</div>
   <p>Paragraph text</p>
</div>
```

I believe the intention of the above was to keep the icon as close to centered on the page as possible, but only floating relative to the paragraph centerline if the paragraph exceeded `--number-of-lines-threshold`.

From memory, I had another approach that instead restricted the floating position by bounding it within a certain buffer at the top/bottom of the paragraph defined by  some other `--number-of-lines-threshold` value.

This will all require some experimentation to decode the earlier experimentation.
